### PR TITLE
Year functions

### PR DESCRIPTION
**Pull request by martinsvalin**
Years implemented in terms of months.

### CODE REVIEW

**Comment by martinsvalin** [comment]
FYI: Since this builds on the inefficient version of `months_after`, I measured test runs with and without calling `10_000 |> years_from_now`. The difference is lost in the noise. `100_000 |> years_from_now` will slow down my test runs by a tenth or two of a second. A million years, and we start seeing up to 1.5s slowdowns.

**Comment by DevL** [comment]
Merge it. Wheter or not we decide to do it, speeding up `months_after` will speed up these functions.

Let's figure out a way to add and test `...from_now` / `...ago` functions. Mock is an aternative, but I've noticed two things.

1. we cannot easily mock `:calendar.universal_time` as it's in a "sticky" module.
2. I'm unsure of the implications of mocking the `now` function when it's already been included in the test module. I'll give it a go.

**Comment by DevL** [comment]
Just as I remembered, `Mock` will effectively replace the entire module with a mock one, only responding to the mocked functions. This leaves us with a few options

1. Throw our hands in the air and ignore testing the functions that are relative to `now`.
2. Extract the call to `:calendar.universal_time` into a separate module that can be mocked.
3. Grab the functions involved from the unmocked module and add them to the mock.
4. Compare the returned result of e.g. `a_month_from_now` to `a_month_after now`.

Of these options, the one I'm least unhappy with is 4. While it effectively duplicates the implementation in the test, it at least is clear and straightforward to reason about. Plus the code is actually tested.

Option 3 is only possible if only public functions are involved. Sure, we _could_ grab the function being tested and shove it into a fake module with a fake `now` and a fake `months_after` that record the call happening but this tightly couples the test to the implementation, more so that option 4  _and_ it's tricky to reason about the test.

Option 2 I strongly dislike as it forces us to make a architecture change for the sole sake of testing _and_ it pollutes the module namespace with yet another module. We didn't like it when trying to macrofying all the things so I doubt we would like it now.

Without further ado, I'll go ahead with option 4, adding tests to the untested functions merged as part of #15 and expand on this PR with tests plus implementations of the equivalent functions for years.

**Comment by martinsvalin** [comment]
I actually like option 4, not just least unlike it. It does echo the implementation, but so does the test for `now`. Nothing really wrong with that, unless the test has to change if the implementation does, and that doesn't seem the case here. The functions that use `now` are really only convenience functions on top of the ones accepting a datetime. They should be tested enough to show that they do indeed work, but other than that the behaviour follows the corresponding one with datetime passed in.

I'm actually considering updating the tests (again), and get rid of `:calendar.time_difference`. That function is, according to the docs, "obsolete". We can instead make a straightforward assertion like `asset a_second_after(@a_datetime) == {{2015, 2, 27}, {18, 45, 31}}`, and `assert a_second_from_now == a_second_after(now)`. To me, it's a good thing that there's "less" going on in the tests as a result.

**Pull request merged**
