### PR TITLE
Conversion functions

### PR DESCRIPTION
**Pull request by DevL**
Addressing #12, this adds the following functions in the new module `GoodTimes.Convert`:

```elixir
datetime_to_date/1
datetime_to_time/1
date_to_datetime/1
```

I considered adding `time_to_datetime/1` for the sake of symmetry, but I'm not sure if it's useful to convert a time of day to the same time of day on January 1, year 0.

Would it be worth shortening `datetime_to_date` / `datetime_to_time` to just `to_date` / `to_time`? It certainly reads nicer, and it could be argued that all our functions, unless explicitly stated, operates on `datetime`s, making the first part of the function names redundant. `date_to_datetime` probably needs to be explicit unless is handles both `date`s and `datetime`s (returning the `datetime` unaltered).

### Update

In the end, the following functions were added:

```elixir
to_date/1
to_time/1
from_date/1
```

### CODE REVIEW

**Comment by martinsvalin** [comment]
I think `to_date` and `to_time` is better. I personally think these functions are borderline out of scope, due to their simplicity. If you have a datetime and care to look at it, it's very obvious how to do this yourself. But the functions do add expressiveness. I'd rather do `datetime |> to_time` than `datetime |> elem 1`.

**Comment by DevL** [comment]
Agreed. I'll change to `to_date` and `to_time`.

**Comment by martinsvalin** [comment]
Would it make sense to have `time |> time_to_datetime` be equivalent to `now |> at time`?

**Comment by DevL** [comment]
Maybe. But then I'd rather see people use `now |> at {10, 30, 45}`.

**Comment by DevL** [comment]
Or `today |> at {10, 30, 45}` (if we add such an alias to `now`).

**Comment by martinsvalin** [comment]
Given these additions, `today` would make sense.

**Comment by DevL** [comment]
Ok, I think it should go into the same place we decide to put `yesteday` and `tomorrow`.

**Comment by martinsvalin** [comment]
rebased

**Comment by DevL** [comment]
Bah. Rebased again. :-D

**Comment by DevL** [comment]
Would `from_date` be a better name than `date_to_datetime` (assuming that we in general use `datetime` internally?

**Comment by martinsvalin** [comment]
Hmm. `from_date`. I like the symmetry with `to_date`. Yes. KBK!

**Comment by DevL** [comment]
[KBK?](http://www.karlstadbk.nu/)

**Comment by martinsvalin** [comment]
Sure, why not. Kör bara kör!

**Pull request merged**
